<?php
// api/download_ahk.php
// Endpoint ini digunakan untuk men-download file AutoHotkey (.ahk) secara aman dari server-side.

session_start();

// 1. Cek Proteksi Session: Apakah user sudah login?
if (!isset($_SESSION['is_logged_in']) || $_SESSION['is_logged_in'] !== true) {
    http_response_code(401);
    echo "Akses ditolak. Silakan login terlebih dahulu.";
    exit;
}

require_once '../config/db.php';
require_once '../config/security.php';

// Ambil app_id dari parameter GET
$appId = isset($_GET['app_id']) ? intval($_GET['app_id']) : 0;
$userId = $_SESSION['user_id'];

if ($appId <= 0) {
    http_response_code(400);
    echo "ID Aplikasi tidak valid!";
    exit;
}

try {
    // 2. CEK OTORISASI: Apakah user ini terdaftar memiliki hak akses ke aplikasi ini?
    $authQuery = "SELECT id FROM user_app_akses WHERE user_id = :user_id AND app_id = :app_id LIMIT 1";
    $authStmt = $pdo->prepare($authQuery);
    $authStmt->execute([
        ':user_id' => $userId,
        ':app_id'  => $appId
    ]);
    
    if (!$authStmt->fetch()) {
        http_response_code(403);
        echo "Anda tidak memiliki hak akses untuk aplikasi ini!";
        exit;
    }

    // 3. AMBIL DETAIL APLIKASI DAN KREDENSIAL
    $query = "SELECT a.nama_app, a.tipe, a.url_atau_path,
                     ka.tipe_kredensial, ka.username_app, ka.password_app_encrypted
              FROM aplikasi a 
              LEFT JOIN kredensial_app ka ON a.id = ka.app_id
              WHERE a.id = :app_id LIMIT 1";
    $stmt = $pdo->prepare($query);
    $stmt->execute([':app_id' => $appId]);
    $app = $stmt->fetch();

    if (!$app) {
        http_response_code(404);
        echo "Aplikasi tidak ditemukan!";
        exit;
    }

    // 4. DEKRIPSI KATA SANDI
    $usernameApp = '';
    $passwordApp = '';

    if (isset($app['tipe_kredensial'])) {
        if ($app['tipe_kredensial'] === 'sama_portal') {
            $usernameApp = $_SESSION['username'];
            $passwordApp = isset($_SESSION['portal_password']) ? $_SESSION['portal_password'] : '';
        } else {
            $usernameApp = $app['username_app'];
            $passwordApp = decrypt_password($app['password_app_encrypted']);
        }
    }

    $appName = $app['nama_app'];
    $appPath = $app['url_atau_path'];
    $appType = $app['tipe'] === 'web' ? 'Web' : 'Desktop';

    // 5. BANGUN AKTIVASI KODE AHK
    $activationCode = "";
    $windowTarget = "";

    // Bersihkan tanda kutip ganda di awal/akhir path
    $cleanedPath = $appPath ? trim(str_replace('"', '', $appPath)) : '';

    if ($appType === 'Desktop') {
        if ($cleanedPath) {
            $parts = preg_split('/[\\/\\\\]/', $cleanedPath);
            $lastPart = end($parts);
            if (preg_match('/\.exe$/i', $lastPart)) {
                $windowTarget = 'ahk_exe ' . $lastPart;
            }
        }
        if (!$windowTarget && $appName) {
            $windowTarget = $appName;
        }
    }

    if ($windowTarget) {
        $activationCode = "; Tunggu sampai window aplikasi muncul, lalu aktifkan dan fokuskan
WinWait, {$windowTarget},, 15
if (ErrorLevel) {
    MsgBox, 48, IT Portal Automation, Timeout menunggu {$appName} terbuka.
    ExitApp
}
WinActivate, {$windowTarget}
WinWaitActive, {$windowTarget},, 10
Sleep, 1500
";
    } else {
        $activationCode = "; Tunggu browser atau window inisialisasi
Sleep, 3000
";
    }

    $ahkCode = "; AutoHotkey Script generated by IT Portal for {$appName}
#NoEnv
SetTitleMatchMode, 2
SendMode Input
SetWorkingDir %A_ScriptDir%

; Meminta hak akses Administrator secara otomatis (Wajib untuk berinteraksi dengan aplikasi UAC/Admin)
if not A_IsAdmin
{
    Run *RunAs \"%A_ScriptFullPath%\"
    ExitApp
}

; Jalankan aplikasi
Run, \"{$cleanedPath}\"
{$activationCode}
; Isi kredensial secara otomatis
Send, {Raw}{$usernameApp}
Sleep, 500
Send, {Tab}
Sleep, 500
Send, {Raw}{$passwordApp}
Sleep, 500
Send, {Enter}

; Keluar setelah selesai untuk menghindari konflik proses UAC di kemudian hari
ExitApp
";

    // 6. SET HEADER DOWNLOAD
    $safeAppName = strtolower(preg_replace('/[^a-z0-9]/', '_', $appName));
    $filename = $safeAppName . "_login.ahk";

    header('Content-Type: application/octet-stream');
    header('Content-Disposition: attachment; filename="' . $filename . '"');
    header('Content-Length: ' . strlen($ahkCode));
    echo $ahkCode;
    exit;

} catch (\PDOException $e) {
    http_response_code(500);
    echo "Terjadi kesalahan database: " . $e->getMessage();
    exit;
}
